apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basicapi-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: basicapi
    spec:
      containers:
      - name: basicapi
        image: kidsan/basic-api
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: basicapi-service
spec:
  selector:
    app: basicapi
  ports:
    - protocol: TCP
      port: 3000
  type: NodePort